"""
Pyramid Node model for hierarchical story structure.
"""
from sqlalchemy import Column, String, Text, Integer, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.db.base_class import Base


class PyramidNode(Base):
    """
    PyramidNode model representing a node in the hierarchical pyramid structure.
    
    The pyramid structure allows for multi-level story organization:
    - Level 0: High-level summary (root)
    - Level 1: Major plot points
    - Level 2: Detailed scenes
    - Level N: Increasingly detailed breakdowns
    """
    
    __tablename__ = "pyramid_nodes"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey("pyramid_nodes.id", ondelete="CASCADE"), nullable=True, index=True)
    
    title = Column(String(500), nullable=False)
    content = Column(Text, nullable=False)
    level = Column(Integer, nullable=False, default=0)  # 0 = root, 1+ = children
    order = Column(Integer, nullable=False, default=0)  # Order among siblings
    
    # BUG-022 FIX: is_generated is Boolean, not String
    is_generated = Column(Boolean, default=False, nullable=False)  # True if generated by LLM
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    project = relationship("Project", backref="pyramid_nodes")
    parent = relationship("PyramidNode", remote_side=[id], backref="children")
    
    # NC-005 FIX: Relationship versions décommentée
    versions = relationship("Version", back_populates="pyramid_node", cascade="all, delete-orphan")
