"""add_pyramid_version_semantic_tag_models

Revision ID: 5b269623668e
Revises: 30583d6b69ae
Create Date: 2025-11-11 06:04:44.640472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b269623668e'
down_revision = '30583d6b69ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyramid_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['pyramid_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyramid_nodes_id'), 'pyramid_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_pyramid_nodes_parent_id'), 'pyramid_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pyramid_nodes_project_id'), 'pyramid_nodes', ['project_id'], unique=False)
    op.create_table('entity_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('is_manual', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_resolutions_id'), 'entity_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_entity_resolutions_project_id'), 'entity_resolutions', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_resolutions_tag_name'), 'entity_resolutions', ['tag_name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('tag_type', sa.Enum('CHARACTER', 'PLACE', 'EVENT', 'THEME', 'NOTE', 'LINK', name='tagtype'), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('syntax', sa.String(length=20), nullable=False),
    sa.Column('resolved_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_document_id'), 'tags', ['document_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_project_id'), 'tags', ['project_id'], unique=False)
    op.create_index(op.f('ix_tags_tag_name'), 'tags', ['tag_name'], unique=False)
    op.create_index(op.f('ix_tags_tag_type'), 'tags', ['tag_type'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('pyramid_node_id', sa.UUID(), nullable=True),
    sa.Column('commit_message', sa.String(length=500), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('metadata_snapshot', sa.Text(), nullable=True),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pyramid_node_id'], ['pyramid_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_document_id'), 'versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_versions_id'), 'versions', ['id'], unique=False)
    op.create_index(op.f('ix_versions_project_id'), 'versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_versions_pyramid_node_id'), 'versions', ['pyramid_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versions_pyramid_node_id'), table_name='versions')
    op.drop_index(op.f('ix_versions_project_id'), table_name='versions')
    op.drop_index(op.f('ix_versions_id'), table_name='versions')
    op.drop_index(op.f('ix_versions_document_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_tags_tag_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_tag_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_project_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_document_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_entity_resolutions_tag_name'), table_name='entity_resolutions')
    op.drop_index(op.f('ix_entity_resolutions_project_id'), table_name='entity_resolutions')
    op.drop_index(op.f('ix_entity_resolutions_id'), table_name='entity_resolutions')
    op.drop_table('entity_resolutions')
    op.drop_index(op.f('ix_pyramid_nodes_project_id'), table_name='pyramid_nodes')
    op.drop_index(op.f('ix_pyramid_nodes_parent_id'), table_name='pyramid_nodes')
    op.drop_index(op.f('ix_pyramid_nodes_id'), table_name='pyramid_nodes')
    op.drop_table('pyramid_nodes')
    # ### end Alembic commands ###
